global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'product_services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['product-services:8080']
        labels:
          application: 'Product Services Application'
  - job_name: 'order_services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['order-services:8080']
        labels:
          application: 'Order Services Application'
  - job_name: 'inventory_services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['inventory-services:8080']
        labels:
          application: 'Inventory Services Application'
  - job_name: 'notification_services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['notification-services:8080']
        labels:
          application: 'Notification Services Application'
